Script started on 2022-11-13 23:39:43-08:00 [TERM="xterm-256color" TTY="/dev/pts/130" COLUMNS="120" LINES="30"]
[?2004h[ncrouch1@cancun hw4]$ echo $u[KUSER
[?2004lncrouch1
[?2004h[ncrouch1@cancun hw4]$ PATH=[K[K[K[K[Kexport PATH="/[K./:$PATH"
[?2004l[?2004h[ncrouch1@cancun hw4]$ echo %[K$p[KPATH
[?2004l./:/usr/lib/java/apache-maven-3.8.6/bin:/usr/lib/java/apache-ant-1.10.12/bin:/data/netid/ncrouch1/.local/bin:/data/netid/ncrouch1/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/lib/java/apache-maven-3.8.6/bin:/usr/lib/java/apache-ant-1.10.12/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
[?2004h[ncrouch1@cancun hw4]$ wget https://courses.cs.washington.edu/courses/cse34[K74/22au/calendar/lecturelist.html
[?2004l--2022-11-13 23:40:55--  https://courses.cs.washington.edu/courses/cse374/22au/calendar/lecturelist.html
Resolving courses.cs.washington.edu (courses.cs.washington.edu)... 128.208.1.193, 2607:4000:200:10::c1
Connecting to courses.cs.washington.edu (courses.cs.washington.edu)|128.208.1.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11687 (11K) [text/html]
Saving to: ‘lecturelist.html.2’

lecturelist.html.2              0%[                                                  ]       0  --.-KB/s               lecturelist.html.2            100%[=================================================>]  11.41K  --.-KB/s    in 0s      

2022-11-13 23:40:55 (142 MB/s) - ‘lecturelist.html.2’ saved [11687/11687]

[?2004h[ncrouch1@cancun hw4]$ geturls output lectude[K[Krelist.html
[?2004l[?2004h[ncrouch1@cancun hw4]$ runanalysis dataout output
[?2004lPerforming wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/hello.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/magic.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/printargs.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/square1.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/control.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/control2.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/fgets.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/argumentdemo.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/dangling.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/pointeradd.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mystery.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mystery1.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mystery2.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mystery3.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mystery4.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/arraydemo.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/arraydynamic.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/factorial_orig.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/factorial_fixed.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/reverse_orig.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/reverse_fixed.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/arrdynamicwrong.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/mysterynum.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/point.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/linkedlist_1.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/linkedlist.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/linkedlistclient.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/debug.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/twice.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/main.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/speak.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/shout.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/curve.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/test.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/for.c
...successful
Performing wordcount measurement on https://courses.cs.washington.edu/courses/cse374/22au/lectures/ccode/testfor.c
...successful
[?2004h[ncrouch1@cancun hw4]$ scapp[K[Ktterplot.R
[?2004l[1] 3397
[1] 94.36111
null device 
          1 
[?2004h[ncrouch1@cancun hw4]$ exit
[?2004lexit

Script done on 2022-11-13 23:41:37-08:00 [COMMAND_EXIT_CODE="0"]

There appears to be a somewhat linear trend in the scatterplot output of runanalysis. There is one exception however with an extremity with high word count in the latter half of the analyzed urls. This draws me to think that as the class progresses the c code files get longer.

The R script prints out two variables, the first is the sum of all the data word counts, the second is the mean word count of all the analyzed urls. The sum represents the total words for all the files. The mean represents the average word count per file calculated by the sum divided by the number of inputs.